### PR TITLE
Delete interpolation

### PR DESCRIPTION
**Pull request by MykolaLevadnyi**

### CODE REVIEW

**Review by R-Mielamud — COMMENTED** [review]
All seems fine, but check places, where table and property names are passed as parameters. It can be incorrect syntax.

**Review by R-Mielamud — APPROVED** [review]
Now you can merge

**Comment by R-Mielamud** [comment]
But be careful with conflicts

**Comment by MykolaLevadnyi** [comment]
Merged from another branch

**Pull request closed without merging**
