### PR TITLE
Add login markup

### PR DESCRIPTION
**Pull request by Nadolnij-Andrii**

### CODE REVIEW

**Comment by anton-matsyshyn** [comment]
I don't think we need password validation on login form. Please, remove it

**Comment by anton-matsyshyn** [comment]
Everything else looks fine. Nice work

**Comment by Nadolnij-Andrii** [comment]
I delete unnesessary validation and change structure for reuse some part of code and styles in registration module. 
And I read in specification that login box can be used in another pages, so I move main code of login in login-box component.

**Comment by anton-matsyshyn** [comment]
LGTM

**Pull request merged**
